# Generated by Django 5.1.7 on 2025-03-13 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('date_edit', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'area',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('date_edit', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('demo', models.BooleanField(default=False)),
                ('date_creat', models.DateField(auto_now_add=True)),
                ('date_edit', models.DateField(auto_now=True)),
                ('area', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=100)),
                ('body', models.TextField()),
                ('volume', models.PositiveIntegerField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.area')),
                ('eksports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eksports', to='main.area')),
                ('imports', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imports', to='main.area')),
            ],
            options={
                'db_table': 'analysis',
            },
        ),
    ]
