# Generated by Django 5.1.7 on 2025-04-06 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_confidence_level_opros_summary_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pest',
            name='damage',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='pest',
            name='protection',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='pest',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
