# Generated by Django 5.1.7 on 2025-04-08 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_pest_damage_pest_protection_alter_pest_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pest',
            name='damage',
        ),
        migrations.RemoveField(
            model_name='pest',
            name='protection',
        ),
    ]
